# Generated by Django 4.2.20 on 2025-05-08 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_phone',
            field=models.CharField(blank=True, help_text="Guest's contact phone number", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_expenses', to='booking.booking'),
        ),
    ]
