# Generated by Django 4.2.20 on 2025-05-12 06:07

from django.db import migrations, models

def set_default_phone(apps, schema_editor):
    # Get the historical Booking model
    Booking = apps.get_model('booking', 'Booking')
    # Update all bookings with NULL guest_phone
    Booking.objects.filter(guest_phone__isnull=True).update(guest_phone="N/A")

class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_expense_category'),
    ]

    operations = [
        # First set default value for NULL guest_phone values
        migrations.RunPython(set_default_phone),
        
        # Update guest_phone field to be required
        migrations.AlterField(
            model_name='booking',
            name='guest_phone',
            field=models.CharField(max_length=20, help_text="Guest's contact phone number"),
        ),
        
        # Remove guest_email field
        migrations.RemoveField(
            model_name='booking',
            name='guest_email',
        ),
    ]
