# Generated by Django 4.2.20 on 2025-05-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_make_guest_phone_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
